#ifndef TOKEN_H
#define TOKEN_H
#include <iostream>

using namespace std;
enum Tipo{LLAVE_D,LLAVE_I,CORCHETE_D,CORCHETE_I,COMA,PUNTO_COMA,PARENTESIS_D,PARENTESIS_I,
           IGUAL,GUION,ADMIRACION,MAS,POR,PLECA,CORRER_I,CORRER_D,ROT,MENOR,MAYOR,PORCENTAJE,
           MENOR_IGUAL,MAYOR_IGUAL,COMPARACION,DISTINTO,AND,OR,PUNTO,ERROR,IDENTIFICADOR,INTCONSTANT,
           BOOLCONSTANT,CADENA,CARACTER,FINAL,KWBOOL,KWBREAK,KWPRINT,KWREAD,KWCONTINUE,
           KWCLASS,KWELSE,KWEXTENDS,KWFALSE,KWFOR,KWIF,KWINT,KWNEW,KWNULL,KWRETURN,KWNOT,KWTRUE,KWVOID,KWWHILE};

class Token
{
public:
    Token();
    string lexema;
    string imprimir();
    Tipo tipo;
};

#endif // TOKEN_H
